In [1449]:
import pandas as pd
import numpy as np
FS=pd.read_csv('FS.csv')
FS

,Country,Alcoholic Beverages,Animal Products,Animal fats,"Aquatic Products, Other",Cereals - Excluding Beer,Eggs,"Fish, Seafood",Fruits - Excluding Wine,Meat,...,Vegetable Oils,Vegetables,Obesity,Undernourished,Confirmed,Deaths,Recovered,Active,Population,Unit (all except Population)
0,Afghanistan,0.0000,21.6397,6.2224,0.0,8.0353,0.6859,0.0327,0.4246,6.1244,...,17.0831,0.3593,4.5,29.8,0.142134,0.006186,0.123374,0.012574,38928000.0,%
1,Albania,0.0000,32.0002,3.4172,0.0,2.6734,1.6448,0.1445,0.6418,8.7428,...,9.2443,0.6503,22.3,6.2,2.967301,0.050951,1.792636,1.123714,2838000.0,%
2,Algeria,0.0000,14.4175,0.8972,0.0,4.2035,1.2171,0.2008,0.5772,3.8961,...,27.3606,0.5145,26.6,3.9,0.244897,0.006558,0.167572,0.070767,44357000.0,%
3,Angola,0.0000,15.3041,1.3130,0.0,6.5545,0.1539,1.4155,0.3488,11.0268,...,22.4638,0.1231,6.8,25,0.061687,0.001461,0.056808,0.003419,32522000.0,%
4,Antigua and Barbuda,0.0000,27.7033,4.6686,0.0,3.2153,0.3872,1.5263,1.2177,14.3202,...,14.4436,0.2469,19.1,NaN,0.293878,0.007143,0.190816,0.095918,98000.0,%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,Venezuela (Bolivarian Republic of),0.0000,16.3261,2.2673,0.0,2.5449,0.6555,0.5707,0.9640,7.0949,...,29.5211,0.1851,25.2,21.2,0.452585,0.004287,0.424399,0.023899,28645000.0,%
166,Vietnam,0.0000,33.2484,3.8238,0.0,3.7155,0.7839,1.1217,0.4079,26.4292,...,5.6211,0.6373,2.1,9.3,0.002063,0.000036,0.001526,0.000501,96209000.0,%
167,Yemen,0.0000,12.5401,2.0131,0.0,11.5271,0.5514,0.3847,0.2564,8.0010,...,23.6312,0.1667,14.1,38.9,0.007131,0.002062,0.004788,0.000282,29826000.0,%
168,Zambia,0.0783,9.6005,1.6113,0.0,14.3225,0.6266,1.0070,0.1343,4.9010,...,15.2848,0.1567,6.5,46.7,0.334133,0.004564,0.290524,0.039045,18384000.0,%
169,Zimbabwe,0.0000,10.3796,2.9543,0.0,9.7922,0.3682,0.2455,0.0614,4.5674,...,26.9396,0.0789,12.3,51.3,0.232033,0.008854,0.190964,0.032214,14863000.0,%

In [1450]:
FS['RevisedConfirmed'] = np.where(FS['Confirmed']>=0.005,'High','Low')
FS.head()

,Country,Alcoholic Beverages,Animal Products,Animal fats,"Aquatic Products, Other",Cereals - Excluding Beer,Eggs,"Fish, Seafood",Fruits - Excluding Wine,Meat,...,Vegetables,Obesity,Undernourished,Confirmed,Deaths,Recovered,Active,Population,Unit (all except Population),RevisedConfirmed
0,Afghanistan,0.0,21.6397,6.2224,0.0,8.0353,0.6859,0.0327,0.4246,6.1244,...,0.3593,4.5,29.8,0.142134,0.006186,0.123374,0.012574,38928000.0,%,High
1,Albania,0.0,32.0002,3.4172,0.0,2.6734,1.6448,0.1445,0.6418,8.7428,...,0.6503,22.3,6.2,2.967301,0.050951,1.792636,1.123714,2838000.0,%,High
2,Algeria,0.0,14.4175,0.8972,0.0,4.2035,1.2171,0.2008,0.5772,3.8961,...,0.5145,26.6,3.9,0.244897,0.006558,0.167572,0.070767,44357000.0,%,High
3,Angola,0.0,15.3041,1.3130,0.0,6.5545,0.1539,1.4155,0.3488,11.0268,...,0.1231,6.8,25,0.061687,0.001461,0.056808,0.003419,32522000.0,%,High
4,Antigua and Barbuda,0.0,27.7033,4.6686,0.0,3.2153,0.3872,1.5263,1.2177,14.3202,...,0.2469,19.1,NaN,0.293878,0.007143,0.190816,0.095918,98000.0,%,High

In [1451]:
test=FS.corr()

In [1452]:
FS.drop(['Country', 'Animal Products','Animal fats','Fruits - Excluding Wine','Meat', 'Miscellaneous', 'Treenuts','Obesity','Deaths','Recovered','Active','Population'], axis=1, inplace=True)
FS

,Alcoholic Beverages,"Aquatic Products, Other",Cereals - Excluding Beer,Eggs,"Fish, Seafood",Milk - Excluding Butter,Offals,Oilcrops,Pulses,Spices,...,Stimulants,Sugar Crops,Sugar & Sweeteners,Vegetal Products,Vegetable Oils,Vegetables,Undernourished,Confirmed,Unit (all except Population),RevisedConfirmed
0,0.0000,0.0,8.0353,0.6859,0.0327,8.2803,0.3103,1.0452,0.1960,0.2776,...,0.0980,0.0000,0.0,28.3684,17.0831,0.3593,29.8,0.142134,%,High
1,0.0000,0.0,2.6734,1.6448,0.1445,17.7576,0.2933,3.1622,0.1148,0.0000,...,0.5270,0.0000,0.0,17.9998,9.2443,0.6503,6.2,2.967301,%,High
2,0.0000,0.0,4.2035,1.2171,0.2008,8.0934,0.1067,1.1983,0.2698,0.1568,...,0.2886,0.0000,0.0,35.5857,27.3606,0.5145,3.9,0.244897,%,High
3,0.0000,0.0,6.5545,0.1539,1.4155,1.2309,0.1539,3.9902,0.3282,0.0103,...,0.1128,0.0000,0.0,34.7010,22.4638,0.1231,25,0.061687,%,High
4,0.0000,0.0,3.2153,0.3872,1.5263,6.6607,0.1347,1.3579,0.0673,0.3591,...,1.0549,0.0000,0.0,22.2995,14.4436,0.2469,NaN,0.293878,%,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,0.0000,0.0,2.5449,0.6555,0.5707,5.5217,0.2082,0.1003,0.1157,0.0000,...,0.0848,0.0000,0.0,33.6855,29.5211,0.1851,21.2,0.452585,%,High
166,0.0000,0.0,3.7155,0.7839,1.1217,0.7520,0.3378,4.2891,0.0765,0.6309,...,0.0829,0.0382,0.0,16.7548,5.6211,0.6373,9.3,0.002063,%,Low
167,0.0000,0.0,11.5271,0.5514,0.3847,1.3463,0.2436,0.7565,0.5001,0.1026,...,0.3718,0.0000,0.0,37.4535,23.6312,0.1667,38.9,0.007131,%,High
168,0.0783,0.0,14.3225,0.6266,1.0070,1.2756,0.1790,9.8915,0.0783,0.1567,...,0.0671,0.0000,0.0,40.3939,15.2848,0.1567,46.7,0.334133,%,High
169,0.0000,0.0,9.7922,0.3682,0.2455,2.1040,0.1315,1.9462,0.1140,0.0526,...,0.1052,0.0000,0.0,39.6248,26.9396,0.0789,51.3,0.232033,%,High

In [1453]:
FS.drop(['Alcoholic Beverages','Aquatic Products, Other','Sugar Crops','Sugar Crops','Sugar & Sweeteners','Unit (all except Population)', 'Undernourished'], axis=1, inplace=True)
FS.head()

,Cereals - Excluding Beer,Eggs,"Fish, Seafood",Milk - Excluding Butter,Offals,Oilcrops,Pulses,Spices,Starchy Roots,Stimulants,Vegetal Products,Vegetable Oils,Vegetables,Confirmed,RevisedConfirmed
0,8.0353,0.6859,0.0327,8.2803,0.3103,1.0452,0.1960,0.2776,0.0490,0.0980,28.3684,17.0831,0.3593,0.142134,High
1,2.6734,1.6448,0.1445,17.7576,0.2933,3.1622,0.1148,0.0000,0.0510,0.5270,17.9998,9.2443,0.6503,2.967301,High
2,4.2035,1.2171,0.2008,8.0934,0.1067,1.1983,0.2698,0.1568,0.1129,0.2886,35.5857,27.3606,0.5145,0.244897,High
3,6.5545,0.1539,1.4155,1.2309,0.1539,3.9902,0.3282,0.0103,0.7078,0.1128,34.7010,22.4638,0.1231,0.061687,High
4,3.2153,0.3872,1.5263,6.6607,0.1347,1.3579,0.0673,0.3591,0.0449,1.0549,22.2995,14.4436,0.2469,0.293878,High

In [1454]:
FS.isnull().sum()

Cereals - Excluding Beer    0
Eggs                        0
Fish, Seafood               0
Milk - Excluding Butter     0
Offals                      0
Oilcrops                    0
Pulses                      0
Spices                      0
Starchy Roots               0
Stimulants                  0
Vegetal Products            0
Vegetable Oils              0
Vegetables                  0
Confirmed                   6
RevisedConfirmed            0
dtype: int64

In [1455]:
FS.Confirmed.fillna(FS.Confirmed.mean(), inplace=True)
FS.isnull().sum()

Cereals - Excluding Beer    0
Eggs                        0
Fish, Seafood               0
Milk - Excluding Butter     0
Offals                      0
Oilcrops                    0
Pulses                      0
Spices                      0
Starchy Roots               0
Stimulants                  0
Vegetal Products            0
Vegetable Oils              0
Vegetables                  0
Confirmed                   0
RevisedConfirmed            0
dtype: int64

In [1456]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder
X=FS.drop(['Confirmed'],axis=1)
Y=FS['Confirmed']
X_train = np.array(X[0:int(0.80*len(X))])
Y_train = np.array(Y[0:int(0.80*len(Y))])
X_test = np.array(X[int(0.80*len(X)):])
Y_test = np.array(Y[int(0.80*len(Y)):])
len(X_train), len(Y_train), len(X_test), len(Y_test)

(136, 136, 34, 34)

In [1457]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC, NuSVC

In [1458]:
NB = GaussianNB()
NLSVM = SVC(kernel='rbf')

In [1459]:
FS.drop(['Confirmed'], axis =1, inplace=True)
FS.head()

,Cereals - Excluding Beer,Eggs,"Fish, Seafood",Milk - Excluding Butter,Offals,Oilcrops,Pulses,Spices,Starchy Roots,Stimulants,Vegetal Products,Vegetable Oils,Vegetables,RevisedConfirmed
0,8.0353,0.6859,0.0327,8.2803,0.3103,1.0452,0.1960,0.2776,0.0490,0.0980,28.3684,17.0831,0.3593,High
1,2.6734,1.6448,0.1445,17.7576,0.2933,3.1622,0.1148,0.0000,0.0510,0.5270,17.9998,9.2443,0.6503,High
2,4.2035,1.2171,0.2008,8.0934,0.1067,1.1983,0.2698,0.1568,0.1129,0.2886,35.5857,27.3606,0.5145,High
3,6.5545,0.1539,1.4155,1.2309,0.1539,3.9902,0.3282,0.0103,0.7078,0.1128,34.7010,22.4638,0.1231,High
4,3.2153,0.3872,1.5263,6.6607,0.1347,1.3579,0.0673,0.3591,0.0449,1.0549,22.2995,14.4436,0.2469,High

In [1460]:
X = FS.drop(['RevisedConfirmed'], axis=1)
Y = FS['RevisedConfirmed']

In [1461]:
import numpy as pd
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder
X_train = np.array(X[0:int(0.80*len(X))])
Y_train = np.array(Y[0:int(0.80*len(Y))])
X_test = np.array(X[int(0.80*len(X)):])
Y_test = np.array(Y[int(0.80*len(Y)):])
len(X_train), len(Y_train), len(X_test), len(Y_test)

(136, 136, 34, 34)

In [1462]:
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

In [1463]:
NB = GaussianNB()
NLSVM = SVC(kernel='rbf')

In [1464]:
NB_fit = NB.fit(X_train, Y_train)
NLSVM_fit = NLSVM.fit(X_train, Y_train)

In [1465]:
NB_pred = NB_fit.predict(X_test)
NLSVM_pred = NLSVM_fit.predict(X_test)

In [1466]:
from sklearn.metrics import accuracy_score
print("Naive Bayes is %f percent accurate" % (accuracy_score(NB_pred, Y_test)*100))
print("Non Linear SVMs is %f percent accurate" % (accuracy_score(NLSVM_pred, Y_test)*100))

Naive Bayes is 76.470588 percent accurate
Non Linear SVMs is 82.352941 percent accurate

In [1467]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
seed=0
cv = KFold(n_splits=5,random_state=2, shuffle=True) 
def return_score(model,X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    score = model.score(X_test, y_test)
    return score
scores = []
model = GaussianNB()
for train_index, test_index in cv.split(X,Y):
    X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.2)
    score = return_score(model,X_train, X_test, y_train, y_test)    
    scores.append(score)
print("Accuracy score in each iteration: {}".format(scores))
print("K-Fold Score: {}".format(np.mean(scores)))

Accuracy score in each iteration: [0.7058823529411765, 0.9411764705882353, 0.9411764705882353, 0.7941176470588235, 0.9117647058823529]
K-Fold Score: 0.8588235294117647

In [1468]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
seed=0
cv = KFold(n_splits=5,random_state=2, shuffle=True) 
def return_score(model,X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    score = model.score(X_test, y_test)
    return score
scores = []
model = SVC()
for train_index, test_index in cv.split(X,Y):
    X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.2)
    score = return_score(model,X_train, X_test, y_train, y_test)    
    scores.append(score)
print("Accuracy score in each iteration: {}".format(scores))
print("K-Fold Score: {}".format(np.mean(scores)))

Accuracy score in each iteration: [0.9117647058823529, 1.0, 0.9705882352941176, 0.9705882352941176, 0.9705882352941176]
K-Fold Score: 0.9647058823529411